/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Episode
import org.openapitools.client.models.Info

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param info 
 * @param results 
 */


data class EpisodesResponse (

    @Json(name = "info")
    val info: Info? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<Episode>? = null

) {


}

