/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param airDate 
 * @param episode 
 * @param characters 
 * @param url 
 * @param created 
 */


data class Episode (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "air_date")
    val airDate: kotlin.String? = null,

    @Json(name = "episode")
    val episode: kotlin.String? = null,

    @Json(name = "characters")
    val characters: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "created")
    val created: kotlin.String? = null

) {


}

