openapi: 3.0.0
info:
  title: Rick and Morty API
  version: 1.0.0
servers:
  - url: https://rickandmortyapi.com/api
paths:
  /episode:
    get:
      summary: Get all episodes
      responses:
        "200":
          description: A list of episodes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EpisodesResponse"
components:
  schemas:
    Info:
      type: object
      properties:
        count: { type: integer }
        pages: { type: integer }
        next: { type: string, nullable: true }
        prev: { type: string, nullable: true }
    Episode:
      type: object
      properties:
        id:        { type: integer }
        name:      { type: string }
        air_date:  { type: string }
        episode:   { type: string }
        characters:
          type: array
          items: { type: string }
        url:       { type: string }
        created:   { type: string }
    EpisodesResponse:
      type: object
      properties:
        info:
          $ref: "#/components/schemas/Info"
        results:
          type: array
          items:
            $ref: "#/components/schemas/Episode"