/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Info

class InfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Info
        //val modelInstance = Info()

        // to test the property `count`
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `pages`
        should("test pages") {
            // uncomment below to test the property
            //modelInstance.pages shouldBe ("TODO")
        }

        // to test the property `next`
        should("test next") {
            // uncomment below to test the property
            //modelInstance.next shouldBe ("TODO")
        }

        // to test the property `prev`
        should("test prev") {
            // uncomment below to test the property
            //modelInstance.prev shouldBe ("TODO")
        }

    }
}
